import { ClientProps, ReportingPeriod } from "../interfaces/interfaces";
import { NewIndiAssociation } from "./individuals";
import { ShareClass } from "./share-classes";

export class Client {
  clientCode: string;
  clientName: string;
  companyNumber: string;
  incorpDate: string;
  accRefMonth: string;
  accRefDate: string;
  nominatedDay: number;
  _senior: string;
  _manager: string;
  _responsibleIndividual: string;
  clientSoftware: string;
  _id?: string;
  shareClasses: ShareClass[];
  directors: NewIndiAssociation[];
  shareholders: NewIndiAssociation[];
  newIndividuals: NewIndiAssociation[];
  existingIndividuals: NewIndiAssociation[];
  currentReportingPeriod: ReportingPeriod;
  previousReportingPeriods: ReportingPeriod[];
  amortBasisGwill: string;
  amortRateGwill: string;
  amortBasisPatsLics: string;
  amortRatePatsLics: string;
  amortBasisDevCosts: string;
  amortRateDevCosts: string;
  amortBasisCompSware: string;
  amortRateCompSware: string;
  depnBasisFholdProp: string;
  depnRateFholdProp: string;
  depnBasisShortLhold: string;
  depnRateShortLhold: string;
  depnBasisLongLhold: string;
  depnRateLongLhold: string;
  depnBasisImprovements: string;
  depnRateImprovements: string;
  depnBasisPlantMachinery: string;
  depnRatePlantMachinery: string;
  depnBasisFixFittings: string;
  depnRateFixFittings: string;
  depnBasisMotorVehicles: string;
  depnRateMotorVehicles: string;
  depnBasisCompEquip: string;
  depnRateCompEquip: string;
  depnBasisOfficeEquip: string;
  depnRateOfficeEquip: string;
  depnBasisIPOwned: string;
  depnRateIPOwned: string;
  depnBasisIPLeased: string;
  depnRateIPLeased: string;
  constructor(client: ClientProps) {
    this.clientCode = client.clientCode;
    this.clientName = client.clientName;
    this.companyNumber = client.companyNumber;
    this.incorpDate = client.incorpDate;
    this.accRefMonth = client.accRefMonth;
    this.accRefDate = client.accRefDate;
    this.nominatedDay = client.nominatedDay;
    this._senior = client._senior;
    this._manager = client._manager;
    this._responsibleIndividual = client._responsibleIndividual;
    this.clientSoftware = client.clientSoftware;
    this._id = client._id;
    this.shareClasses = client.shareClasses ? client.shareClasses.map((i) => new ShareClass(i)) : [];
    this.directors = client.directors ? client.directors.map((i) => new NewIndiAssociation(i)) : [];
    this.shareholders = client.shareholders ? client.shareholders.map((i) => new NewIndiAssociation(i)) : [];
    this.newIndividuals = client.newIndividuals ? client.newIndividuals.map((i) => new NewIndiAssociation(i)) : [];
    this.existingIndividuals = client.existingIndividuals
      ? client.existingIndividuals.map((i) => new NewIndiAssociation(i))
      : [];
    this.currentReportingPeriod = client.currentReportingPeriod;
    this.previousReportingPeriods = client.previousReportingPeriods;
    this.amortBasisGwill = client.amortBasisGwill;
    this.amortRateGwill = client.amortRateGwill;
    this.amortBasisPatsLics = client.amortBasisPatsLics;
    this.amortRatePatsLics = client.amortRatePatsLics;
    this.amortBasisDevCosts = client.amortBasisDevCosts;
    this.amortRateDevCosts = client.amortRateDevCosts;
    this.amortBasisCompSware = client.amortBasisCompSware;
    this.amortRateCompSware = client.amortRateCompSware;
    this.depnBasisFholdProp = client.depnBasisFholdProp;
    this.depnRateFholdProp = client.depnRateFholdProp;
    this.depnBasisShortLhold = client.depnBasisShortLhold;
    this.depnRateShortLhold = client.depnRateShortLhold;
    this.depnBasisLongLhold = client.depnBasisLongLhold;
    this.depnRateLongLhold = client.depnRateLongLhold;
    this.depnBasisImprovements = client.depnBasisImprovements;
    this.depnRateImprovements = client.depnRateImprovements;
    this.depnBasisPlantMachinery = client.depnBasisPlantMachinery;
    this.depnRatePlantMachinery = client.depnRatePlantMachinery;
    this.depnBasisFixFittings = client.depnBasisFixFittings;
    this.depnRateFixFittings = client.depnRateFixFittings;
    this.depnBasisMotorVehicles = client.depnBasisMotorVehicles;
    this.depnRateMotorVehicles = client.depnRateMotorVehicles;
    this.depnBasisCompEquip = client.depnBasisCompEquip;
    this.depnRateCompEquip = client.depnRateCompEquip;
    this.depnBasisOfficeEquip = client.depnBasisOfficeEquip;
    this.depnRateOfficeEquip = client.depnRateOfficeEquip;
    this.depnBasisIPOwned = client.depnBasisIPOwned;
    this.depnRateIPOwned = client.depnRateIPOwned;
    this.depnBasisIPLeased = client.depnBasisIPLeased;
    this.depnRateIPLeased = client.depnRateIPLeased;
  }
}
