import { PreliminaryClientProps } from "../interfaces/interfaces";
import { NewIndividual } from "./new-individual";
import { PreliminaryShareClass } from "./share-classes";

export class PreliminaryClient {
  clientCode: string;
  clientName: string;
  companyNumber: string;
  incorpDate: string;
  accRefMonth: string;
  accRefDate: string;
  nominatedDay: number;
  _senior: string;
  _manager: string;
  _responsibleIndividual: string;
  clientSoftware: string;
  _id?: string;
  shareClasses: PreliminaryShareClass[];
  directors: NewIndividual[];
  shareholders: NewIndividual[];
  newIndividuals: NewIndividual[];
  existingIndividuals: NewIndividual[];
  amortBasisGwill: string;
  amortRateGwill: string;
  amortBasisPatsLics: string;
  amortRatePatsLics: string;
  amortBasisDevCosts: string;
  amortRateDevCosts: string;
  amortBasisCompSware: string;
  amortRateCompSware: string;
  depnBasisFholdProp: string;
  depnRateFholdProp: string;
  depnBasisShortLhold: string;
  depnRateShortLhold: string;
  depnBasisLongLhold: string;
  depnRateLongLhold: string;
  depnBasisImprovements: string;
  depnRateImprovements: string;
  depnBasisPlantMachinery: string;
  depnRatePlantMachinery: string;
  depnBasisFixFittings: string;
  depnRateFixFittings: string;
  depnBasisMotorVehicles: string;
  depnRateMotorVehicles: string;
  depnBasisCompEquip: string;
  depnRateCompEquip: string;
  depnBasisOfficeEquip: string;
  depnRateOfficeEquip: string;
  depnBasisIPOwned: string;
  depnRateIPOwned: string;
  depnBasisIPLeased: string;
  depnRateIPLeased: string;
  constructor(prelimClient: PreliminaryClientProps) {
    this.clientCode = prelimClient.clientCode;
    this.clientName = prelimClient.clientName;
    this.companyNumber = prelimClient.companyNumber;
    this.incorpDate = prelimClient.incorpDate;
    this.accRefMonth = prelimClient.accRefMonth;
    this.accRefDate = prelimClient.accRefDate;
    this.nominatedDay = prelimClient.nominatedDay;
    this._senior = prelimClient._senior;
    this._responsibleIndividual = prelimClient._responsibleIndividual;
    this.clientSoftware = prelimClient.clientSoftware;
    this._id = prelimClient._id;
    this.shareClasses = prelimClient.shareClasses.map((i) => new PreliminaryShareClass(i));
    this.directors = prelimClient.directors.map((i) => new NewIndividual(i));
    this.shareholders = prelimClient.shareholders.map((i) => new NewIndividual(i));
    this.newIndividuals = prelimClient.newIndividuals.map((i) => new NewIndividual(i));
    this.existingIndividuals = prelimClient.existingIndividuals.map((i) => new NewIndividual(i));
    this.amortBasisGwill = prelimClient.amortBasisGwill;
    this.amortRateGwill = prelimClient.amortRateGwill;
    this.amortBasisPatsLics = prelimClient.amortBasisPatsLics;
    this.amortRatePatsLics = prelimClient.amortRatePatsLics;
    this.amortBasisDevCosts = prelimClient.amortBasisDevCosts;
    this.amortRateDevCosts = prelimClient.amortRateDevCosts;
    this.amortBasisCompSware = prelimClient.amortBasisCompSware;
    this.amortRateCompSware = prelimClient.amortRateCompSware;
    this.depnBasisFholdProp = prelimClient.depnBasisFholdProp;
    this.depnRateFholdProp = prelimClient.depnRateFholdProp;
    this.depnBasisShortLhold = prelimClient.depnBasisShortLhold;
    this.depnRateShortLhold = prelimClient.depnRateShortLhold;
    this.depnBasisLongLhold = prelimClient.depnBasisLongLhold;
    this.depnRateLongLhold = prelimClient.depnRateLongLhold;
    this.depnBasisImprovements = prelimClient.depnBasisImprovements;
    this.depnRateImprovements = prelimClient.depnRateImprovements;
    this.depnBasisPlantMachinery = prelimClient.depnBasisPlantMachinery;
    this.depnRatePlantMachinery = prelimClient.depnRatePlantMachinery;
    this.depnBasisFixFittings = prelimClient.depnBasisFixFittings;
    this.depnRateFixFittings = prelimClient.depnRateFixFittings;
    this.depnBasisMotorVehicles = prelimClient.depnBasisMotorVehicles;
    this.depnRateMotorVehicles = prelimClient.depnRateMotorVehicles;
    this.depnBasisCompEquip = prelimClient.depnBasisCompEquip;
    this.depnRateCompEquip = prelimClient.depnRateCompEquip;
    this.depnBasisOfficeEquip = prelimClient.depnBasisOfficeEquip;
    this.depnRateOfficeEquip = prelimClient.depnRateOfficeEquip;
    this.depnBasisIPOwned = prelimClient.depnBasisIPOwned;
    this.depnRateIPOwned = prelimClient.depnRateIPOwned;
    this.depnBasisIPLeased = prelimClient.depnBasisIPLeased;
    this.depnRateIPLeased = prelimClient.depnRateIPLeased;
  }
}
