import { ClientMapping, Transaction as TransactionProps } from "../interfaces/interfaces";
import { TransactionUpdate } from "./transaction-update";

export class Transaction implements TransactionProps {
  value: number;
  transactionType: string;
  transactionDate: Date | string;
  transactionDateExcel: number;
  transactionNumber: number;
  transactionBatchNumber: number;
  iteration: number;
  iterations: {
    iteration: number;
    transactionDate: string;
    cerysCode: number;
    narrative: string;
  }[];
  narrative: string;
  user: string;
  clientTB: boolean;
  clientNominalCode: number;
  clientNominalName: string;
  clientAdjustment: boolean;
  journal: boolean;
  reviewJournal: boolean;
  finalJournal: boolean;
  workbookRef: string;
  worksheetRef: string;
  dateCreated: string;
  defaultClientMapping: ClientMapping;
  activeClientMapping: ClientMapping;
  updates: TransactionUpdate[];
  cerysCode: number;
  cerysName: string;
  cerysShortName: string;
  cerysExcelName: string;
  cerysCategory: string;
  cerysSubCategory: string | null;
  assetCategory: string | null;
  assetCategoryNo: number | null;
  assetSubCategory: string | null;
  assetSubCatCode: number | null;
  assetCodeType: string | null;
  regColNameOne: string | null;
  regColNameTwo: string | null;
  altCategory: string | null;
  defaultSign: string | null;
  clientAdj: boolean;
  closeOffCode: number;
  _id: string;

  constructor(transaction: Transaction) {
    this.value = transaction.value;
    this.transactionType = transaction.transactionType;
    this.transactionDate = transaction.transactionDate;
    this.transactionDateExcel = transaction.transactionDateExcel;
    this.transactionNumber = transaction.transactionNumber;
    this.transactionBatchNumber = transaction.transactionBatchNumber;
    this.iteration = transaction.iteration;
    this.iterations = transaction.iterations;
    this.narrative = transaction.narrative;
    this.user = transaction.user;
    this.clientTB = transaction.clientTB;
    this.clientNominalCode = transaction.clientNominalCode;
    this.clientAdjustment = transaction.clientAdjustment;
    this.journal = transaction.journal;
    this.reviewJournal = transaction.reviewJournal;
    this.finalJournal = transaction.finalJournal;
    this.workbookRef = transaction.workbookRef;
    this.worksheetRef = transaction.worksheetRef;
    this.dateCreated = transaction.dateCreated;
    this.defaultClientMapping = transaction.defaultClientMapping;
    this.activeClientMapping = transaction.activeClientMapping;
    this.updates = transaction.updates;
    this.cerysCode = transaction.cerysCode;
    this.cerysName = transaction.cerysName;
    this.cerysShortName = transaction.cerysShortName;
    this.cerysExcelName = transaction.cerysExcelName;
    this.cerysCategory = transaction.cerysCategory;
    this.cerysSubCategory = transaction.cerysSubCategory;
    this.assetSubCatCode = transaction.assetSubCatCode;
    this.assetCodeType = transaction.assetCodeType;
    this.regColNameOne = transaction.regColNameOne;
    this.regColNameTwo = transaction.regColNameTwo;
    this.altCategory = transaction.altCategory;
    this.defaultSign = transaction.defaultSign;
    this.clientAdj = transaction.clientAdj;
    this.closeOffCode = transaction.closeOffCode;
    this._id = transaction._id;
  }
}
