export const colNumToLetter = (numberCols: number) => {
  switch (numberCols) {
    case 1:
      return "A";
    case 2:
      return "B";
    case 3:
      return "C";
    case 4:
      return "D";
    case 5:
      return "E";
    case 6:
      return "F";
    case 7:
      return "G";
    case 8:
      return "H";
    case 9:
      return "I";
    case 10:
      return "J";
    case 11:
      return "K";
    case 12:
      return "L";
    case 13:
      return "M";
    case 14:
      return "N";
    case 15:
      return "O";
    case 16:
      return "P";
    case 17:
      return "Q";
    case 18:
      return "R";
    case 19:
      return "S";
    case 20:
      return "T";
    case 21:
      return "U";
    case 22:
      return "V";
    case 23:
      return "W";
    case 24:
      return "X";
    case 25:
      return "Y";
    case 26:
      return "Z";
    case 27:
      return "AA";
    case 28:
      return "AB";
    case 29:
      return "AC";
    case 30:
      return "AD";
    case 31:
      return "AE";
    case 32:
      return "AF";
    case 33:
      return "AG";
    case 34:
      return "AH";
    case 35:
      return "AI";
    case 36:
      return "AJ";
    case 37:
      return "AK";
    case 38:
      return "AL";
    case 39:
      return "AM";
    case 40:
      return "AN";
    case 41:
      return "AO";
    case 42:
      return "AP";
    case 43:
      return "AQ";
    case 44:
      return "AR";
    case 45:
      return "AS";
    case 46:
      return "AT";
    case 47:
      return "AU";
    case 48:
      return "AV";
    case 49:
      return "AW";
    case 50:
      return "AX";
    case 51:
      return "AY";
    case 52:
      return "AZ";
    case 53:
      return "BA";
    case 54:
      return "BB";
    case 55:
      return "BC";
    case 56:
      return "BD";
    case 57:
      return "BE";
    case 58:
      return "BF";
    case 59:
      return "BG";
    case 60:
      return "BH";
    case 61:
      return "BI";
    case 62:
      return "BJ";
    case 63:
      return "BK";
    case 64:
      return "BL";
    case 65:
      return "BM";
    case 66:
      return "BN";
    case 67:
      return "BO";
    case 68:
      return "BP";
    case 69:
      return "BQ";
    case 70:
      return "BR";
    case 71:
      return "BS";
    case 72:
      return "BT";
    case 73:
      return "BU";
    case 74:
      return "BV";
    case 75:
      return "BW";
    case 76:
      return "BX";
    case 77:
      return "BY";
    case 78:
      return "BZ";
    case 79:
      return "CA";
    case 80:
      return "CB";
    case 81:
      return "CC";
    case 82:
      return "CD";
    case 83:
      return "CE";
    case 84:
      return "CF";
    case 85:
      return "CG";
    case 86:
      return "CH";
    case 87:
      return "CI";
    case 88:
      return "CJ";
    case 89:
      return "CK";
    case 90:
      return "CL";
    case 91:
      return "CM";
    case 92:
      return "CN";
    case 93:
      return "CO";
    case 94:
      return "CP";
    case 95:
      return "CQ";
    case 96:
      return "CR";
    case 97:
      return "CS";
    case 98:
      return "CT";
    case 99:
      return "CU";
    case 100:
      return "CV";
    default:
      return null;
  }
};

export const colLetterToNum = (letterCols) => {
  switch (letterCols) {
    case "A":
      return 1;
    case "B":
      return 2;
    case "C":
      return 3;
    case "D":
      return 4;
    case "E":
      return 5;
    case "F":
      return 6;
    case "G":
      return 7;
    case "H":
      return 8;
    case "I":
      return 9;
    case "J":
      return 10;
    case "K":
      return 11;
    case "L":
      return 12;
    case "M":
      return 13;
    case "N":
      return 14;
    case "O":
      return 15;
    case "P":
      return 16;
    case "Q":
      return 17;
    case "R":
      return 18;
    case "S":
      return 19;
    case "T":
      return 20;
    case "U":
      return 21;
    case "V":
      return 22;
    case "W":
      return 23;
    case "X":
      return 24;
    case "Y":
      return 25;
    case "Z":
      return 26;
    case "AA":
      return 27;
    case "AB":
      return 28;
    case "AC":
      return 29;
    case "AD":
      return 30;
    case "AE":
      return 31;
    case "AF":
      return 32;
    case "AG":
      return 33;
    case "AH":
      return 34;
    case "AI":
      return 35;
    case "AJ":
      return 36;
    case "AK":
      return 37;
    case "AL":
      return 38;
    case "AM":
      return 39;
    case "AN":
      return 40;
    case "AO":
      return 41;
    case "AP":
      return 42;
    case "AQ":
      return 43;
    case "AR":
      return 44;
    case "AS":
      return 45;
    case "AT":
      return 46;
    case "AU":
      return 47;
    case "AV":
      return 48;
    case "AW":
      return 49;
    case "AX":
      return 50;
    case "AY":
      return 51;
    case "AZ":
      return 52;
    case "BA":
      return 53;
    case "BB":
      return 54;
    case "BC":
      return 55;
    case "BD":
      return 56;
    case "BE":
      return 57;
    case "BF":
      return 58;
    case "BG":
      return 59;
    case "BH":
      return 60;
    case "BI":
      return 61;
    case "BJ":
      return 62;
    case "BK":
      return 63;
    case "BL":
      return 64;
    case "BM":
      return 65;
    case "BN":
      return 66;
    case "BO":
      return 67;
    case "BP":
      return 68;
    case "BQ":
      return 69;
    case "BR":
      return 70;
    case "BS":
      return 71;
    case "BT":
      return 72;
    case "BU":
      return 73;
    case "BV":
      return 74;
    case "BW":
      return 75;
    case "BX":
      return 76;
    case "BY":
      return 77;
    case "BZ":
      return 78;
    case "CA":
      return 79;
    case "CB":
      return 80;
    case "CC":
      return 81;
    case "CD":
      return 82;
    case "CE":
      return 83;
    case "CF":
      return 84;
    case "CG":
      return 85;
    case "CH":
      return 86;
    case "CI":
      return 87;
    case "CJ":
      return 88;
    case "CK":
      return 89;
    case "CL":
      return 90;
    case "CM":
      return 91;
    case "CN":
      return 92;
    case "CO":
      return 93;
    case "CP":
      return 94;
    case "CQ":
      return 95;
    case "CR":
      return 96;
    case "CS":
      return 97;
    case "CT":
      return 98;
    case "CU":
      return 99;
    case "CV":
      return 100;
    default:
      return null;
  }
};
