import { FSCategoryBS, FSCategoryPL } from "../interfaces/interfaces";
import {
  CAP_RED_RES_CAT,
  CASH_CAT,
  DEBTORS_CAT,
  FAI_CAT,
  FIN_ASS_CAT,
  FV_RES_CAT,
  IFA_CAT,
  IP_CAT,
  LT_CRED_CAT,
  MI_CAT,
  OR1_CAT,
  OR2_CAT,
  OR3_CAT,
  OR4_CAT,
  OR5_CAT,
  PROVS_CAT,
  SHARE_CAP_CAT,
  SHARE_PREM_CAT,
  ST_CRED_CAT,
  STOCKS_CAT,
  TFA_CAT,
} from "./accounts-categories-bs";
import {
  ADMIN_EXES_CAT,
  COS_CAT,
  DIST_COSTS_CAT,
  INT_PAY_CAT,
  INT_REC_CAT,
  OOI_CAT,
  TO_CAT,
  VAL_ADJ_CAT,
} from "./accounts-categories-pl";

export const accountsCategories: (FSCategoryBS | FSCategoryPL)[] = [
  IFA_CAT,
  TFA_CAT,
  FAI_CAT,
  IP_CAT,
  STOCKS_CAT,
  DEBTORS_CAT,
  FIN_ASS_CAT,
  CASH_CAT,
  ST_CRED_CAT,
  LT_CRED_CAT,
  PROVS_CAT,
  SHARE_CAP_CAT,
  SHARE_PREM_CAT,
  CAP_RED_RES_CAT,
  FV_RES_CAT,
  OR1_CAT,
  OR2_CAT,
  OR3_CAT,
  OR4_CAT,
  OR5_CAT,
  MI_CAT,
  TO_CAT,
  COS_CAT,
  OOI_CAT,
  VAL_ADJ_CAT,
  DIST_COSTS_CAT,
  ADMIN_EXES_CAT,
  INT_REC_CAT,
  INT_PAY_CAT,
];
