import { STANDARD_NUMBER_FORMAT } from "./worksheet-formats";

export const DEFINED_COLS = {
  transNo: {
    type: "transNo",
    isMutable: false,
    isQuasiMutable: false,
    format: [["0"]],
    isUnique: true,
    key: ["transactionNumber"],
  },
  date: {
    type: "date",
    isMutable: true,
    isQuasiMutable: false,
    format: [["dd/mm/yyyy"]],
    isUnique: false,
    key: ["transactionDateExcel"],
  },
  transType: {
    type: "transType",
    isMutable: false,
    isQuasiMutable: false,
    format: [[""]],
    isUnique: false,
    key: ["transactionType"],
  },
  cerysCode: {
    type: "cerysCode",
    isMutable: true,
    isQuasiMutable: false,
    format: [["0"]],
    isUnique: false,
    key: ["cerysCode"],
  },
  cerysName: {
    type: "cerysName",
    isMutable: false,
    isQuasiMutable: true,
    format: [[""]],
    isUnique: false,
    key: ["cerysName"],
  },
  clientCode: {
    type: "clientCode",
    isMutable: false,
    isQuasiMutable: false,
    format: [["0"]],
    isUnique: false,
    key: ["clientNominalCode"],
  },
  clientCodeName: {
    type: "clientCodeName",
    isMutable: false,
    isQuasiMutable: false,
    format: [[""]],
    isUnique: false,
    key: ["clientNominalName"],
  },
  cerysNarrative: {
    type: "cerysNarrative",
    isMutable: true,
    isQuasiMutable: false,
    format: [[""]],
    isUnique: false,
    key: ["narrative"],
  },
  value: {
    type: "value",
    isMutable: false,
    isQuasiMutable: false,
    format: STANDARD_NUMBER_FORMAT,
    isUnique: false,
    key: ["value"],
  },
  clientCodeMapping: {
    type: "clientCodeMapping",
    isMutable: true,
    isQuasiMutable: false,
    format: [["0"]],
    isUnique: false,
    key: ["activeClientMapping", "clientCode"],
  },
  clientCodeNameMapping: {
    type: "clientCodeNameMapping",
    isMutable: false,
    isQuasiMutable: true,
    format: [[""]],
    isUnique: false,
    key: ["activeClientMapping", "clientCodeName"],
  },
  clientNarrative: {
    type: "clientNarrative",
    isMutable: false,
    isQuasiMutable: false,
    format: [[""]],
    isUnique: false,
    key: undefined,
  },
  depnBasis: {
    type: "depnBasis",
    isMutable: true,
    isQuasiMutable: false,
    format: [[""]],
    isUnique: false,
    key: undefined,
  },
  depnRate: {
    type: "depnRate",
    isMutable: true,
    isQuasiMutable: false,
    format: [["0"]],
    isUnique: false,
    key: undefined,
  },
  depnCharge: {
    type: "depnCharge",
    isMutable: false,
    isQuasiMutable: true,
    format: STANDARD_NUMBER_FORMAT,
    isUnique: false,
    key: undefined,
  },
};
