export const DEFINED_COLS = {
  transNo: {
    type: "transNo",
    isMutable: false,
    isQuasiMutable: false,
    format: "0",
    isUnique: true,
  },
  date: {
    type: "date",
    isMutable: true,
    isQuasiMutable: false,
    format: "dd/mm/yyyy",
    isUnique: false,
  },
  transType: {
    type: "transType",
    isMutable: false,
    isQuasiMutable: false,
    format: "",
    isUnique: false,
  },
  cerysCode: {
    type: "cerysCode",
    isMutable: true,
    isQuasiMutable: false,
    format: "0",
    isUnique: false,
  },
  cerysName: {
    type: "cerysName",
    isMutable: false,
    isQuasiMutable: true,
    format: "",
    isUnique: false,
  },
  clientCode: {
    type: "clientCode",
    isMutable: false,
    isQuasiMutable: false,
    format: "0",
    isUnique: false,
  },
  clientCodeName: {
    type: "clientCodeName",
    isMutable: false,
    isQuasiMutable: false,
    format: "",
    isUnique: false,
  },
  cerysNarrative: {
    type: "cerysNarrative",
    isMutable: true,
    isQuasiMutable: false,
    format: "",
    isUnique: false,
  },
  value: {
    type: "value",
    isMutable: false,
    isQuasiMutable: false,
    format: "#,##0.00;(#,##0.00);-",
    isUnique: false,
  },
  clientCodeMapping: {
    type: "clientCodeMapping",
    isMutable: true,
    isQuasiMutable: false,
    format: "0",
    isUnique: false,
  },
  clientCodeNameMapping: {
    type: "clientCodeNameMapping",
    isMutable: false,
    isQuasiMutable: true,
    format: "",
    isUnique: false,
  },
  clientNarrative: {
    type: "clientNarrative",
    isMutable: false,
    isQuasiMutable: false,
    format: "",
    isUnique: false,
  },
  depnBasis: {
    type: "depnBasis",
    isMutable: true,
    isQuasiMutable: false,
    format: "",
    isUnique: false,
  },
  depnRate: {
    type: "depnRate",
    isMutable: true,
    isQuasiMutable: false,
    format: "0",
    isUnique: false,
  },
  depnCharge: {
    type: "depnCharge",
    isMutable: false,
    isQuasiMutable: true,
    format: "#,##0.00;(#,##0.00);-",
    isUnique: false,
  },
};
